### ISSUE TITLE
Unable to build completely both in VS 2015 and command line

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/fsharp-dnx#15]
I am probably missing something obvious.
Command line Build works...

```
FSharp.Dnx -> C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\bin\Debug\FSharp.Dnx.1.0.0-beta-t151020192739.nupkg
FSharp.Dnx -> C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\bin\Debug\FSharp.Dnx.1.0.0-beta-t151020192739.symbols.nupkg

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

..., but tests are not discovered

```
info: Exec
info:   program: cmd
info:   commandline: /C dnx test
info:   workingdir: test\FSharp.Dnx.Test
xUnit.net DNX Runner (32-bit DNX 4.5.1)
  Discovering: FSharp.Dnx.Test
System.IO.FileLoadException: Could not load file or assembly 'FSharp.Dnx.Test, Version=0.0.0.0' or one of its dependencies. Uncaught exception during type initialization. (Exception from HRESULT: 0x80131534)
System.TypeInitializationException: The type initializer for 'Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker' threw an exception.
System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Compiler-Service>.$Service' threw an exception.
System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Compiler-Service>.$Microsoft.FSharp.Compiler.Lexhelp' threw an exception.
System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Core>.$Prim-types' threw an exception.
System.IO.FileNotFoundException: Could not find file 'FSharp.Core.resources'.
```

In VS 2015, `FSharp.Dnx` is buildable, but `FSharp.Dnx.Test` is not:

```
Starting  Microsoft.DNX.TestHost [C:\Users\david.podhola\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15921\bin\dnx.exe --appbase "C:\Users\david.podhola\S\fsharp-dnx\test\FSharp.Dnx.Test" Microsoft.DNX.ApplicationHost --port 2396 Microsoft.DNX.TestHost --port 2608]
Connected to Microsoft.Framework.TestHost
Discovering tests in 'C:\Users\david.podhola\S\fsharp-dnx\test\FSharp.Dnx.Test\project.json'
Error discovering tests in 'C:\Users\david.podhola\S\fsharp-dnx\test\FSharp.Dnx.Test\project.json'\r\nSystem.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: System.NotSupportedException: Specified method is not supported.
   at Microsoft.Dnx.Compilation.DesignTime.DesignTimeProjectReference.EmitAssembly(String outputPath)
   at FSharp.Dnx.FSharpCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver) in C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\FSharpCompiler.cs:line 96
   at FSharp.Dnx.FSharpProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver) in C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\FSharpProjectCompiler.cs:line 44
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name)
   at Microsoft.Dnx.Runtime.Compilation.RuntimeLibraryExporter.GetExport(String name)
   at Microsoft.Dnx.TestHost.TestServices.CreateTestServices(IServiceProvider applicationServices, Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass2_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: System.NotSupportedException: Specified method is not supported.
   at Microsoft.Dnx.Compilation.DesignTime.DesignTimeProjectReference.EmitAssembly(String outputPath)
   at FSharp.Dnx.FSharpCompiler.CompileProject(CompilationProjectContext projectContext, IEnumerable`1 incomingReferences, IEnumerable`1 incomingSourceReferences, Func`1 resourcesResolver) in C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\FSharpCompiler.cs:line 96
   at FSharp.Dnx.FSharpProjectCompiler.CompileProject(CompilationProjectContext projectContext, Func`1 referenceResolver, Func`1 resourcesResolver) in C:\Users\david.podhola\S\fsharp-dnx\src\FSharp.Dnx\FSharpProjectCompiler.cs:line 44
   at Microsoft.Dnx.Compilation.LibraryExporter.<>c__DisplayClass17_0.<ExportProject>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Dnx.Compilation.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Dnx.Compilation.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Dnx.Compilation.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Dnx.Compilation.LibraryExporter.ExportProject(ProjectDescription project, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(LibraryDescription library, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name, String aspect)
   at Microsoft.Dnx.Compilation.LibraryExporter.GetExport(String name)
   at Microsoft.Dnx.Runtime.Compilation.RuntimeLibraryExporter.GetExport(String name)
   at Microsoft.Dnx.TestHost.TestServices.CreateTestServices(IServiceProvider applicationServices, Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass2_0.<<Main>b__0>d.MoveNext()<---

```

Thanks!

**Comment by Alxandr** [comment]
First of all, it seems you might be lacking `FSharp.Core` from the test running output. Secondly, building in VS does not generally work unfortunately. It **might** work if you rope in `FSharp.Dnx` from nuget, instead of from sources, but I wouldn't hold my breath. Command line is currently the only way. And last I checked, it's not really something that I can fix. DNX is still beta software, and they are pressed for time to get 1.0 out the door. So while adding support for other languages actually work (which is great), there are aspects of it (like VS) that probably won't until they have time to design scenarios like that (probably around the time when they decide to add support for VB to DNX).

**Comment by davidpodhola** [comment]
Thanks for you reply. I am totally OK with build not working in VS and yes, I know DNX is still beta, we are building a bigger project on it and there is a new surprise comming almost every day...
Maybe I am totally off the track.

Not sure what could the problem with `FSharp.Core` be, but at the beginning  I can see 

```
Adding C:\Users\david.podhola\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15921\bin to process PATH
```

and then

```
  Using Package dependency FSharp.Core 4.0.0.1
    Source: C:\Users\david.podhola\.dnx\packages\FSharp.Core\4.0.0.1
    File: lib\net40\FSharp.Core.dll
```

It seems the test are not discovered because they are not build at all. No `bin\Debug` folder under tests.
When I run `dnu build` I get
`Error: The type initializer for 'Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker' threw an exception.` Seems be the same as thrown by VS 2015.

**Comment by Alxandr** [comment]
First of all, there should be no assemblies under `bin\Debug`. DNX doesn't produce assemblies unless you explicitly ask for it (using `dnu build`). As for the error you're seeing, it's hard to say. It might be a new bug introduced somewhere (like new release of DNX). I just kicked off the CI with a new build to see if it works or not. It should at least be a good representative, cause it won't be "stuff on my PC" that makes it build or break at least. If it doesn't build I guess I have some investigating to do. If it does build, well, I still have some investigating to do :P. Am I right in understanding that it's this project you're trying to build (using the `build.cmd` file)?

**Comment by davidpodhola** [comment]
You are right, sorry for not being clear. 
The second part of my previous post was about running `dnu build` in the `FSharp.Dnx.Test` folder. No `artifacts` created there. Also might be related to a new release of DNX, I tried both `1.0.0-rc1-15921` and `1.0.0-beta8`.
Yes, I am trying to use `build.cmd`, see the animated gif attached for the whole build.
Also I would like to help although I must admit the whole DNX is quite new for me.

![fsharp-dnx](https://cloud.githubusercontent.com/assets/436605/10629680/4b5b4e8a-77d1-11e5-8335-aff05359949d.gif)

**Comment by davidpodhola** [comment]
Screenshot of just the end of the build using `build.cmd`
![fsharp dnx test build failed](https://cloud.githubusercontent.com/assets/436605/10629776/20f6df3c-77d2-11e5-93d0-b88e4500f0e5.PNG)

**Comment by davidpodhola** [comment]
For the text result of running `build.cmd` see https://gist.github.com/davidpodhola/13457c9cae21bf2e6bac

**Comment by xperiandri** [comment]
I have a similar error with RC1
`Error  NU1002  The dependency FSharp.Core 4.0.0.1 in project HelloFSharp does not support framework DNX,Version=v4.5.1.    HelloFSharp C:\Users\Андрій\Dev\GitHub\fsharp-dnx\src\FSharp.Dnx\project.json 9`

**Comment by Alxandr** [comment]
This project is deprecated as DNX is going away. Check out dotnet CLI instead :)

**Comment by xperiandri** [comment]
Switch to master that targets RC2?

**Comment by Alxandr** [comment]
No, there is no branch/release that works with the newest stuff, because dotnet cli already have f# support

**Comment by xperiandri** [comment]
Is it possible to write ASP.NET Core apps with F# on RC2?

**Comment by Alxandr** [comment]
Yes, it is my understanding that it should be possible. And this project is not part of the equation.
