### ISSUE TITLE
Unable to load application or execute command 'web'.

### ISSUE THREAD

**Issue by evilz** [fsprojects/fsharp-dnx#5]
From a clean env,
DNVM install
DNVM use default
DNU restore
DNX . Web

System.InvalidOperationException: Unable to load application or execute command
'web'.
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundExcepti
on(DefaultHost host, String applicationName, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

C:\Users\Vincent\Downloads\YoloDev.Dnx.FSharp-master\YoloDev.Dnx.FSharp-master\s
ample\HelloFSharp>dnx . kestrel
System.InvalidOperationException: Unable to load application or execute command
'kestrel'.
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundExcepti
on(DefaultHost host, String applicationName, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

**Comment by Alxandr** [comment]
HelloFSharp is not a web application. It does not have `web` or `kestrel` commands defined. Try `dnx . run`.

**Comment by Alxandr** [comment]
I'm closing this issue. Please let me know if you can't get it to work.

**Comment by evilz** [comment]
Thank. 
Still not good :(  
Witch dnx version are you using ?
Got many many errors on  `1.0.0-beta6-12032`

**Comment by Alxandr** [comment]
Can you show me the output? Also, what command are you running, and where?

**Comment by evilz** [comment]
> dnvm list

Active Version           Runtime Architecture Location                       Alias

---

```
   1.0.0-beta4       clr     x64          C:\Users\Vincent\.dnx\runtimes
   1.0.0-beta4       clr     x86          C:\Users\Vincent\.dnx\runtimes
   1.0.0-beta4       coreclr x64          C:\Users\Vincent\.dnx\runtimes
   1.0.0-beta4       coreclr x86          C:\Users\Vincent\.dnx\runtimes
   1.0.0-beta6-12032 clr     x86          C:\Users\Vincent\.dnx\runtimes default
```

> dnvm use default
> dnu restore
> dnu . run

too many errors to list here.

show you last one 

```
C:\YoloDev.Dnx.FSharp-master\src\YoloDev.Dnx.FSharp\FSharpCompiler.cs(
234,13): error CS0103: The name 'PlatformHelper' does not exist in the current context
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext load
Context)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

Maybe I have problem on dnx installation ^^

**Comment by Alxandr** [comment]
Try `dnx --version` and `dnx . run` (not `dnu . run`). You might be running on `beta4`, which will not work. Also, there is obviously the chance that the later versions of DNX broke something, I haven't tested it in ~1 week (meaning it's highly likely something broke ^^).
